services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    api:
        build: 
            context: ./API
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3